//Traer todos los elementos y las cajas a js

let contenedorIniciar = document.getElementsByClassName("contenedorIniciar";)
const BOTONiniciar= document.getElementById("entrar")
let contenedorFormulario= document.getElementsByClassName("contenedorFormulario")
let inputUser=document.getElementById("usuario")
let inputPassword=document.getElementById("contraseña")
let contenedorOpciones=document.getElementsByClassName("opciones")
const BOTONsaldo=document.getElementById("saldo")
const BOTONretiro=document.getElementById("Retirar")
const BOTONdeposito=document.getElementById("Depositar")
const BOTONsalir1=document.getElementById("salir1")
let contenedorSaldo=document.getElementsByClassName("caja_saldo")
const BOTONsalir2=document.getElementById("salir2")
const BOTONregresar0=document.getElementById("regresar0")
let contenedorRetirar=document.getElementsByClassName("caja_retirar")
let inputRetiro=document.getElementById("cantidadRetiro")
const BOTONconfirmarRet=document.getElementById("confirmarRetiro")
const BOTONregresar1=document.getElementById("Regresar")